version: '3'

# Глобальные переменные проекта
vars:
  GO_VERSION: '1.25.1'

  BIN_DIR: '{{.ROOT_DIR}}/bin'
  GOLANGCI_LINT: '{{.BIN_DIR}}/golangci-lint'
  GCI: '{{.BIN_DIR}}/gci'
  GOFUMPT: '{{.BIN_DIR}}/gofumpt'
  ENVDIR: '{{.ROOT_DIR}}/deploy/env'

  MODULES: http collector platform
  SERVICES: http collector platform

tasks:
  deps:update:
    desc: "Обновление зависимостей в go.mod во всех модулях"
    cmds:
      - |
        echo "🔄 Обновление зависимостей в go.mod во всех модулях"
        for mod in {{.MODULES}}; do
          if [ -d "$mod" ]; then
            echo "🔄 Обновление зависимостей в $mod"
            (cd "$mod" && go mod tidy -compat=1.25.1) || exit 1
          fi
        done
